<?php
module_load_include('php', 'cpsc471prj', 'includes/User');
module_load_include('php', 'cpsc471prj', 'includes/Season');
module_load_include('php', 'cpsc471prj', 'includes/Renter');


/**
 * Implements hook_permission()
 * 
 * Sets the different permissions that drupal will use for building menus
 * 
 * this prevents renters from seeing manager links,
 * and  managers from seeing renter links
 * @return string[][]
 * 		The permission descriptions
 */
function cpsc471prj_permission() {
	return array (
		'renter' => array (
			'title' => 'Renter',
			'description' => 'Permission to check if user is renter'
		),
		'manager' => array (
			'title' => 'Manager',
			'description' => 'Permission to check if user is manager'
		),
	);
}

/**
 * Implements hook_menu()
 * 
 * Describes the various paths for accessing pages of the website
 * 
 * @return array
 */
function cpsc471prj_menu(){
	$items = array();
	
	$items['scc'] = array (
		'title' => 'Home',
		'description' => 'Main page',
		'page callback' => 'drupal_get_form',
		'page arguments' => array (
			'home_form',	
		),
		'menu_name' => 'cpsc',
		'access callback' => 'cpsc471_access',
		'access arguments' => array (
		
		),
	);
	
	$items['scc/renter'] = array (
		'title' => 'Renter',
		'description' => 'Rental main page',
		'page callback' => 'drupal_get_form',
		'page arguments' => array (
			'renter_home_form',
		),
		'menu_name' => 'cpsc',
		'access callback' => 'cpsc471_access',
		'access arguments' => array (
			'renter'
		),
	);
	
	$items['scc/manager'] = array (
		'title' => 'Manager',
		'description' => 'Manager main page',
		'page callback' => 'drupal_get_form',
		'page arguments' => array (
				'manager_home_form',
		),
		'menu_name' => 'cpsc',
		'access callback' => 'cpsc471_access',
		'access arguments' => array (
				'manager'
		),
	);
	
	$items['scc/manager/seasons'] = array (
		'title' => 'View Seasons',
		'description' => 'Manager main page',
		'page callback' => 'drupal_get_form',
		'page arguments' => array (
				'manager_view_seasons_form',
		),
		'menu_name' => 'cpsc',
		'access callback' => 'cpsc471_access',
		'access arguments' => array (
				'manager'
		),
	);
	
	$items['scc/manager/seasons/new'] = array (
		'title' => 'Create Season',
		'description' => 'Manager main page',
		'page callback' => 'drupal_get_form',
		'page arguments' => array (
				'manager_create_seasons_form',
		),
		'menu_name' => 'cpsc',
		'access callback' => 'cpsc471_access',
		'access arguments' => array (
				'manager'
		),
		'type' => MENU_LOCAL_ACTION
	);
	
	$items['scc/manager/cottages'] = array (
		'title' => 'View Seasons',
		'description' => 'Manager main page',
		'page callback' => 'drupal_get_form',
		'page arguments' => array (
				'manager_view_cottages_form',
		),
		'menu_name' => 'cpsc',
		'access callback' => 'cpsc471_access',
		'access arguments' => array (
				'manager'
		),
	);
	
	
	$items['test/%'] = array (
		'title' => 'Test',
		'description' => 'This is a test',
		'page callback' => 'drupal_get_form',
		'page arguments' => array (
				'myform', 1,
		),
		'access callback' => true,
		
	);
	return $items;
}

/**
 * Access callback for menu building
 * 
 * Accepts n argument, where arguments are permission names
 * 
 * @return boolean
 * 		true if the user has all the provided permissions,
 * 		false otherwise
 */
function cpsc471_access() {
	//get the arguments provided
	$arguments = func_get_args();
	$user = new User();
	//check each argument
	foreach($arguments as $permission) {
		if(!$user->hasPermission($permission)) {
			return false;
		}
	}
	
	return true;
}

/**
 * Main router for the website
 * 
 * If user is logs in checks them for manager role and redirects there,
 * otherwise directs to user page
 * 
 * If they are not logged in, it will provided a form for creating 
 * an account
 * 
 */
function home_form($form, &$form_state) {
	
	$user = new User();
	
	if(user_is_logged_in()) {
		if($user->hasRole('Renter')) {
			drupal_goto('scc/renter');
		}
		
		if($user->hasRole('Manager')) {
			drupal_goto('scc/manager');
		}
	}
	
	drupal_set_title('Create Account');
	
	$form['name'] = array (
		'#title' => 'Name',
		'#type' => 'textfield',
		'#required' => true,
	);
	
	$form['email'] = array (
		'#title' => 'eMail',
		'#type' => 'textfield',
		'#required' => true,
	);
	
	$form['password'] = array (
		'#title' => 'Password',
		'#type' => 'textfield',
		'#required' => true,
	);
	
	$form['credit_card'] = array (
		'#title' => 'Credit Card Number',
		'#type' => 'textfield',
		'#required' => true,
	);
	
	$form['phone_number'] = array (
			'#title' => 'Phone number',
			'#type' => 'textfield',
			'#required' => true,
	);
	
	$form['submit'] = array (
		'#type' => 'submit',
		'#value' => 'Create Account',
		'#submit' => array(
				'home_form_submit'
		),
		'#validate' => array(
			'home_form_validate',
		)
	);
	
	return $form;
}

function home_form_validate($form, $form_state){
	if(!User::isCreditCardValid($form_state['values']['credit_card'])){
		form_set_error('credit_card', "Invalid Credit Card Format.");
	}
	if(!User::isPhoneNumberValid($form_state['values']['phone_number'])){
		form_set_error('phone_number', "Invalid Phone number Format.");
	}
	if(!User::isEmailValid($form_state['values']['email'])){
		form_set_error('email', "Invalid email format");
	}
}


/**
 * Creates a new account in both the drupal user table and the rental_account table
 */
function home_form_submit($form, $form_state) {
	
	$email = $form_state['values']['email'];
	$password = $form_state['values']['password'];
	$name = $form_state['values']['name'];
	$credit_card = $form_state['values']['credit_card'];//Not saved yet
	$phone = $form_state['values']['phone_number'];
	
	$newUserForDrupal = array(
		'name' => $email,
		'pass' => $password,
		'mail' => $email,
		'status' => 1,
		'init' => $email,
		'is_new' => true,
	);
	
	$DrupalUser = user_save('', $newUserForDrupal);
	
	$NewRenterInfo = array(
			'account_uid' => $DrupalUser->uid,
			'name' => $name,
			'id_adult' => 1,
	);
	
	$NewRenter = new Renter('new');
	
	
	$NewRenter->setCopy($NewRenterInfo);
	$NewRenter->storeToDB();
	
	
	//$NewRenter->AddNewRenter($NewRenterInfo);
	
	$NewUserInfo = array(
		'uid' => $DrupalUser->uid,
		'credit_card' => $credit_card,
		'phone' => $phone,
		'primary_renter_id' => $NewRenter->getProperty('id'),
	);
	
	$YourGuy = new User();
	$YourGuy->AddNewUser($NewUserInfo);
	
}



function manager_home_form($form, &$form_state) {
	$form['test'] = array (
			'#markup' => 'manager',
	);

	return $form;
}

function manager_view_seasons_form($form, &$form_state) {
	
}

function manager_create_seasons_form($form, &$form_state) {
	
	$date = '2016-01-01';
	$format = 'Y-m-d';
	/*
	 * 
		'#title' => 'Password',
		'#type' => 'textfield',
		'#required' => true,
	 */
	// gather list of information needed for a season
	$form['name'] = array(
			'#title' => 'Season name',
			'#type' => 'textfield',
			'#required' => true,
	);
	$form['start_time'] = array(
			'#title' => 'Start of season',
			'#type' => 'date_popup',
			'#default_value' => $date,
			'#date_format' => $format,
			'#required' => true,
	);
	$form['end_time'] = array(
			'#title' => 'End of season',
			'#type' => 'date_popup',
			'#default_value' => $date,
			'#date_format' => $format,
			'#required' => true,
	);
	
	// call function which adds the form contents to the seasons DB
	$form['submit'] = array (
			'#type' => 'submit',
			'#value' => 'Add Season',
			'#submit' => array(
					'create_season_form_submit'
			),
	);
	
	return $form;
}

function create_season_form_submit($form, $form_state){

	$seasonVals = array(
			'name' => $form_state['values']['name'],
			'start' => strtotime($form_state['values']['start_time']),
			'end' => strtotime($form_state['values']['end_time']),
	);
	scc_debug($seasonVals);

	$s = new Season($seasonVals);
	$s->setCopy($seasonVals);
	$s->storeToDB();

}

/**
 * Form with a table of cottages to view
 * @param unknown $form
 * @param unknown $form_state
 */
function manager_view_cottages_form($form, &$form_state) {
	
}

function renter_home_form($form, &$form_state) {
	$form['test'] = array (
		'#markup' => 'renter',	
	);

	return $form;
}







////////////////////////////
//Demo code below this line
////////////////////////////

/**
 * Prints all arguments as drupal messages
 */
function scc_debug() {
	
	$args = func_get_args();
	
	foreach($args as $arg) {
		drupal_set_message('<pre>' . print_r($arg, true) . '</pre>', 'warning');
	}
	
}


function myform($form, &$form_state, $number) {
	
	db_query("SELECT * FROM Users");
	

	if(isset($form_state['storage']['save_value'])) {
		$number = $form_state['storage']['save_value'];
		$number *= 2;
	}
	
	
	$form['ex'] = array (
		'#prefix' => '<div id="my_div">',
		'#markup' => $number,	
		'#suffix' => '</div>',
	);
	
	$form_state['storage']['save_value'] = intval($number);
	
	$form['button'] = array (
		'#type' => 'fieldset',
		'#title' => 'fred',
		
		
			
		
			
		'button2' => array (
			'#type' => 'button',
			'#value' => 'fish',
				'#ajax' => array (
						'callback' => 'my_ajax',
						'wrapper' => 'my_div',
				),
		),
	);
	
	$form['textfield6'] = array (
		'#type' => 'textfield',	
	);
	
	$form['submit'] = array (
		'#type' => 'submit',
		'#value' => 'Submit',
			
			
		'#validate' => array('validate'),
		'#submit' => array('submit'),
	);
	
	return $form;
}

function validate($form, &$form_state) {
	$form_state['values']['textfield6'] = intval($form_state['values']['textfield6'] );
	
	if($form_state['values']['textfield6'] == 0) {
		form_set_error('textfield6', "stop");
	}
}

function submit($form, &$form_state) {
	drupal_set_message($form_state['values']['textfield6']);
	drupal_goto('');
}

function my_ajax($form, $form_state) {
	return $form['ex'];
}
?>