<?php
module_load_include('php', 'cpsc471prj', 'includes/tools');

function cpsc471prj_permissions() {
	
}

function cpsc471prj_menu(){
	$items = array();
	
	$items['cpsc'] = array (
		'title' => 'Home',
		'description' => 'Main page',
		'page callback' => 'drupal_get_form',
		'page arguments' => array (
			'home_form',	
		),
		'menu_name' => 'cpsc',
		'access callback' => true,
	);
	
	$items['test/%'] = array (
		'title' => 'Test',
		'description' => 'This is a test',
		'page callback' => 'drupal_get_form',
		'page arguments' => array (
				'myform', 1,
		),
		'access callback' => true,
		
	);
	return $items;
}

/**
 * Main router for the website
 * 
 * If user is logs in checks them for manager role and redirects there,
 * otherwise directs to user page
 * 
 * If they are not logged in, it will provided a form for creating 
 * an account
 * 
 */
function home_form($form, &$form_state) {
	
	if(user_is_logged_in()) {
		if(user_has_role()) {
			
		}
	}
	
	global $user;
	
	
	
	
	
	return $form;
}






////////////////////////////
//Demo code below this line
////////////////////////////

function myform($form, &$form_state, $number) {
	
	db_query("SELECT * FROM Users");
	

	if(isset($form_state['storage']['save_value'])) {
		$number = $form_state['storage']['save_value'];
		$number *= 2;
	}
	
	
	$form['ex'] = array (
		'#prefix' => '<div id="my_div">',
		'#markup' => $number,	
		'#suffix' => '</div>',
	);
	
	$form_state['storage']['save_value'] = intval($number);
	
	$form['button'] = array (
		'#type' => 'fieldset',
		'#title' => 'fred',
		
		
			
		
			
		'button2' => array (
			'#type' => 'button',
			'#value' => 'fish',
				'#ajax' => array (
						'callback' => 'my_ajax',
						'wrapper' => 'my_div',
				),
		),
	);
	
	$form['textfield6'] = array (
		'#type' => 'textfield',	
	);
	
	$form['submit'] = array (
		'#type' => 'submit',
		'#value' => 'Submit',
			
			
		'#validate' => array('validate'),
		'#submit' => array('submit'),
	);
	
	return $form;
}

function validate($form, &$form_state) {
	$form_state['values']['textfield6'] = intval($form_state['values']['textfield6'] );
	
	if($form_state['values']['textfield6'] == 0) {
		form_set_error('textfield6', "stop");
	}
}

function submit($form, &$form_state) {
	drupal_set_message($form_state['values']['textfield6']);
	drupal_goto('');
}

function my_ajax($form, $form_state) {
	return $form['ex'];
}
?>